[profile.default]
solc_version = "0.8.26"
evm_version = "shanghai"
auto_detect_solc = false
deny_warnings = true
optimizer = true
optimizer_runs = 400 # fails at 1_000 because certain contracts become too large
src = 'src'
out = 'out'
libs = ['dependencies']
include_paths = ['utils']
verbosity = 1
via_ir = false
remappings = [
    "/=src/",
    "forge-std/=dependencies/forge-std-1.9.2/src/",
    "@openzeppelin/contracts/=dependencies/openzeppelin-contracts-5.0.2/contracts/",
    "@openzeppelin/contracts-upgradeable/=dependencies/openzeppelin-contracts-upgradeable-5.0.2/contracts/",
    "@solady/=dependencies/solady-0.0.231/src/",
]
auto_detect_remappings = false
match-path = "test/**/*.t.sol"
match-contract = "Test$"
ffi = false
fs_permissions = [
    { access = "read-write", path = "./deployments" },
    { access = "read", path = "./out" },
    { access = "read", path = "./config" },
]

[profile.evm_paris]
evm_version = "paris"

[profile.evm_london]
evm_version = "london"

[profile.ci]
verbosity = 4

[profile.ci.fuzz]
verbosity = 4
runs = 256

[fuzz]
runs = 256
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[invariant]
runs = 30
depth = 15
fail_on_revert = true

[soldeer]
remappings_generate = false
remappings_regenerate = false
remappings_version = false
remappings_prefix = ""
recursive_deps = false

[dependencies]
"forge-std" = { version = "1.9.2", git = "https://github.com/foundry-rs/forge-std.git", rev = "58d30519826c313ce47345abedfdc07679e944d1" }
"openzeppelin-contracts" = { version = "5.0.2", git = "https://github.com/OpenZeppelin/openzeppelin-contracts.git", rev = "dbb6104ce834628e473d2173bbc9d47f81a9eec3" }
"openzeppelin-contracts-upgradeable" = { version = "5.0.2", git = "https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable.git", rev = "723f8cab09cdae1aca9ec9cc1cfa040c2d4b06c1" }
"solady" = { version = "0.0.231", git = "https://github.com/Vectorized/solady.git", rev = "2907b5036b9b3489891e69b49adba24c793940d4" }

# See more config options https://book.getfoundry.sh/reference/config/